In [262]:
import pandas as pd
import numpy as np

In [263]:
def load_dataset(filename):
    BASE_DIR = './data'
    EXTENSION = '.csv'
    TARGET_PATH = f'{BASE_DIR}/{filename}{EXTENSION}'
    try:
        return pd.read_csv(TARGET_PATH)
    except FileNotFoundError:
        return None
    except UnicodeDecodeError:
        return pd.read_csv(TARGET_PATH, encoding='euc-kr')

In [264]:
df = load_dataset('입출항')

df.shape

(272904, 30)

In [265]:
df = df[['청코드', '선박키', '입항연도', '입항회수', '업체명', '선박종류', '선박명', '출항예정일시', '입항일시', '출항일시']]

df

# 출항일시 - 입항일시 : 실제 머물렀던 시간
# 출항일시 - 출항예정일시 : Delay된 시간

,청코드,선박키,입항연도,입항회수,업체명,선박종류,선박명,출항예정일시,입항일시,출항일시
0,20,9256391,2019,2,벤라인에이전시즈코리아주식회사,41.0,X-PRESS COTOPAXI,2019-10-18 15:00,2019-10-17 14:00,2019-10-18 14:00
1,20,3FNH6,2019,3,(주)반도마리타임,55.0,SAEHAN AURORA,2019-10-16 09:00,2019-10-15 19:00,2019-10-16 10:00
2,20,DSPC5,2019,7,(주)진웅마리타임,39.0,DONGBANG SAPPHIRE,2019-10-15 18:00,2019-10-14 06:00,2019-10-14 16:00
3,20,960771,2019,42,유정해운(주),52.0,제96유정호,2019-10-08 05:35,2019-09-26 15:50,2019-10-08 05:35
4,20,9248227,2019,43,(주)팬스타,42.0,PANSTAR GENIE,2019-06-27 12:00,2019-06-26 20:00,2019-06-27 12:00
...,...,...,...,...,...,...,...,...,...,...
272899,20,785874,2023,15,금성호,69.0,2금성호,2023-09-12 12:00,2023-09-11 13:05,2023-09-19 15:25
272900,20,785874,2023,16,금성호,69.0,2금성호,2023-11-04 12:00,2023-11-03 08:37,2023-12-04 08:54
272901,20,785874,2023,17,금성호,69.0,2금성호,2023-12-05 12:00,2023-12-04 16:05,2023-12-04 16:06
272902,20,D9SV,2023,26,해강선박,61.0,재영88호,2023-12-28 12:00,2023-12-27 08:55,2024-01-04 11:25
272903,20,31466,2022,1,NaN,77.0,NaN,NaN,2022-12-26 00:00,2023-01-09 00:00

In [266]:
df.duplicated().sum()

np.int64(0)

In [267]:
df.shape

# 현재 row가 272,904개인데 결측치 갯수가 2,256개 있어서 270,648이 맞는지 확인해야 한다.

(272904, 10)

In [268]:
df.dropna()

df

,청코드,선박키,입항연도,입항회수,업체명,선박종류,선박명,출항예정일시,입항일시,출항일시
0,20,9256391,2019,2,벤라인에이전시즈코리아주식회사,41.0,X-PRESS COTOPAXI,2019-10-18 15:00,2019-10-17 14:00,2019-10-18 14:00
1,20,3FNH6,2019,3,(주)반도마리타임,55.0,SAEHAN AURORA,2019-10-16 09:00,2019-10-15 19:00,2019-10-16 10:00
2,20,DSPC5,2019,7,(주)진웅마리타임,39.0,DONGBANG SAPPHIRE,2019-10-15 18:00,2019-10-14 06:00,2019-10-14 16:00
3,20,960771,2019,42,유정해운(주),52.0,제96유정호,2019-10-08 05:35,2019-09-26 15:50,2019-10-08 05:35
4,20,9248227,2019,43,(주)팬스타,42.0,PANSTAR GENIE,2019-06-27 12:00,2019-06-26 20:00,2019-06-27 12:00
...,...,...,...,...,...,...,...,...,...,...
272899,20,785874,2023,15,금성호,69.0,2금성호,2023-09-12 12:00,2023-09-11 13:05,2023-09-19 15:25
272900,20,785874,2023,16,금성호,69.0,2금성호,2023-11-04 12:00,2023-11-03 08:37,2023-12-04 08:54
272901,20,785874,2023,17,금성호,69.0,2금성호,2023-12-05 12:00,2023-12-04 16:05,2023-12-04 16:06
272902,20,D9SV,2023,26,해강선박,61.0,재영88호,2023-12-28 12:00,2023-12-27 08:55,2024-01-04 11:25
272903,20,31466,2022,1,NaN,77.0,NaN,NaN,2022-12-26 00:00,2023-01-09 00:00

In [269]:
df['출항일시'] = pd.to_datetime(df['출항일시'])

df['출항일시'].idxmax

<bound method Series.idxmax of 0        2019-10-18 14:00:00
1        2019-10-16 10:00:00
2        2019-10-14 16:00:00
3        2019-10-08 05:35:00
4        2019-06-27 12:00:00
                 ...
272899   2023-09-19 15:25:00
272900   2023-12-04 08:54:00
272901   2023-12-04 16:06:00
272902   2024-01-04 11:25:00
272903   2023-01-09 00:00:00
Name: 출항일시, Length: 272904, dtype: datetime64[us]>

In [270]:
# 입출항.csv 데이터가 2023-01-09까지라 병목현상 분석에 부적합하다고 판단 폐기처리

In [271]:
df = load_dataset('입항신고')

In [272]:
df.shape

(247056, 24)

In [273]:
df.columns

# 항구명, 년도, 항차, 계산장소시설코드, 계선장소명, 외내항구분, 입항일자, 입항목적, 출항예정일시

Index(['항구명', '호출부호', '선박명', '년도', '항차', '신고일자', '허가일자', '계선장소시설코드', '계선장소명',
       '총톤수', '국제총톤수', '외내항구분', '선박국적', '선박종류', '입항일자', '입항목적', '최초출항지항구코드',
       '최초출항지항구명', '출항예정일시', '전출항지출항일시', '전출항지항구코드', '전출항지항구명', '상태구분',
       '정보생성일시'],
      dtype='str')

In [274]:
df = df[['항구명', '년도', '항차', '계선장소시설코드', '계선장소명', '외내항구분', '입항일자', '입항목적', '출항예정일시']]

In [275]:
df.duplicated().sum()

np.int64(21337)

In [276]:
df = df.drop_duplicates()

print(df.shape)

(225719, 9)

In [277]:
# 중복치만큼 정확히 빠졌는지 확인
df.shape

(225719, 9)

In [278]:
df['입항일자'] = pd.to_datetime(df['입항일자'])
df['출항예정일시'] = pd.to_datetime(df['출항예정일시'])

# 예정 대기 시간 = 출항예정일시 - 입항일자로 정의한다.(실제 출항예정일시에 관한 데이터 확보가 어렵기 때문)

In [279]:
df.info()

<class 'pandas.DataFrame'>
Index: 225719 entries, 0 to 247055
Data columns (total 9 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   항구명       225719 non-null  str
 1   년도        225719 non-null  int64
 2   항차        225719 non-null  int64
 3   계선장소시설코드  225719 non-null  str
 4   계선장소명     225719 non-null  str
 5   외내항구분     225719 non-null  str
 6   입항일자      225719 non-null  datetime64[us]
 7   입항목적      225485 non-null  str
 8   출항예정일시    225719 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(2), str(5)
memory usage: 17.2 MB

In [280]:
df['출항예정일시'].dt.year.unique()

array([2024, 2023, 2025, 2022, 2021, 2004, 2005, 2006, 2424, 2014, 2027,
       2202, 2020, 2026, 2404, 2017, 2040, 2018, 2204, 2034, 2019, 2042,
       2824, 3024, 2008, 2015, 2054, 2007, 2050, 2028, 2205, 2001, 2016,
       2825, 2525, 2035, 2055, 2029], dtype=int32)

In [281]:
df[df['출항예정일시'].dt.year > 2025]

df = df[~(df['출항예정일시'].dt.year > 2025)]

df.shape

(225565, 9)

In [282]:
df = df[~(df['출항예정일시'].dt.year < 2023)]

In [283]:
df['입항일자'].dt.year.unique()

array([2024, 2023, 2022, 2020, 2021, 2019, 2025, 2016, 2011], dtype=int32)

In [284]:
df = df[~(df['입항일자'].dt.year < 2023)]

In [286]:
df.head(2)

,항구명,년도,항차,계선장소시설코드,계선장소명,외내항구분,입항일자,입항목적,출항예정일시
0,부산,2024,4,MBS05,신선대부두 5선석,외항,2024-05-01 03:00:00,양적하,2024-05-02 05:00:00
1,군산,2024,1,MB601,6부두 1선석,외항,2024-04-28 03:42:00,양하,2024-05-02 17:00:00

In [289]:
df = df[df['항구명'] == '부산']

In [ ]:
df['예정대기시간'] = df['출항예정일시'] - df['입항일자']

,항구명,년도,항차,계선장소시설코드,계선장소명,외내항구분,입항일자,입항목적,출항예정일시,예정대기시간
0,부산,2024,4,MBS05,신선대부두 5선석,외항,2024-05-01 03:00:00,양적하,2024-05-02 05:00:00,1 days 02:00:00
3,부산,2024,3,MSN06,신항 2부두 3선석,외항,2024-05-01 04:15:00,양적하,2024-05-02 07:00:00,1 days 02:45:00
4,부산,2024,1,MSN02,신항 1부두 2선석,외항,2024-05-01 07:53:00,적하,2024-05-01 22:00:00,0 days 14:07:00
8,부산,2024,4,MS402,신항 4부두 2선석,외항,2024-04-30 21:40:00,양적하,2024-05-01 23:00:00,1 days 01:20:00
34,부산,2024,14,MB602,자성대부두 62선석,외항,2024-04-30 12:45:00,양적하,2024-05-01 07:00:00,0 days 18:15:00
...,...,...,...,...,...,...,...,...,...,...
247048,부산,2025,487,MK202,감천 2부두 2선석,내항,2025-07-10 12:55:00,기타,2025-07-10 15:50:00,0 days 02:55:00
247049,부산,2025,488,*WN01,남항 물량장,내항,2025-07-10 16:25:00,기타,2025-07-11 07:50:00,0 days 15:25:00
247050,부산,2025,489,MQC01,한진 중공업 안벽,내항,2025-07-11 08:15:00,기타,2025-07-11 11:00:00,0 days 02:45:00
247051,부산,2025,1,WAN03,남외항 N-3박지,외항,2025-07-31 15:00:00,선용품적재,2025-07-31 16:00:00,0 days 01:00:00
247052,부산,2025,25,WAE02,E박지 E2 묘지,내항,2025-07-29 09:00:00,양하,2025-07-31 08:00:00,1 days 23:00:00

In [ ]:
df['예정대기시간'].median() # 21H

Timedelta('0 days 21:00:00')

In [294]:
df[df['예정대기시간'] > df['예정대기시간'].median()]

,항구명,년도,항차,계선장소시설코드,계선장소명,외내항구분,입항일자,입항목적,출항예정일시,예정대기시간
0,부산,2024,4,MBS05,신선대부두 5선석,외항,2024-05-01 03:00:00,양적하,2024-05-02 05:00:00,1 days 02:00:00
3,부산,2024,3,MSN06,신항 2부두 3선석,외항,2024-05-01 04:15:00,양적하,2024-05-02 07:00:00,1 days 02:45:00
8,부산,2024,4,MS402,신항 4부두 2선석,외항,2024-04-30 21:40:00,양적하,2024-05-01 23:00:00,1 days 01:20:00
46,부산,2024,17,*NB01,남부민방파제,내항,2024-04-19 14:50:00,기타,2024-04-30 05:25:00,10 days 14:35:00
49,부산,2024,17,MB604,자성대부두 64선석,외항,2024-05-01 07:50:00,양적하,2024-05-02 10:00:00,1 days 02:10:00
...,...,...,...,...,...,...,...,...,...,...
247033,부산,2025,33,MW501,5물량장 1선석,내항,2025-07-28 19:15:00,단순경유,2025-07-31 11:35:00,2 days 16:20:00
247039,부산,2025,4,WAN03,남외항 N-3박지,외항,2025-07-18 11:15:00,양하,2025-07-22 17:38:00,4 days 06:23:00
247045,부산,2025,23,WAN01,남외항 N-1박지,내항,2025-07-23 17:35:00,기타,2025-07-29 00:05:00,5 days 06:30:00
247047,부산,2025,486,*WN01,남항 물량장,내항,2025-07-08 16:05:00,기타,2025-07-10 12:15:00,1 days 20:10:00
247052,부산,2025,25,WAE02,E박지 E2 묘지,내항,2025-07-29 09:00:00,양하,2025-07-31 08:00:00,1 days 23:00:00

In [ ]:
df_outer = df[df['외내항구분'] == '외항'].copy() # (28,078, 10)
df_inner = df[df['외내항구분'] == '내항'].copy() # (26,504, 10) # total = 54,582

In [304]:
df_outer[df_outer['예정대기시간'] > df['예정대기시간'].median()]

,항구명,년도,항차,계선장소시설코드,계선장소명,외내항구분,입항일자,입항목적,출항예정일시,예정대기시간
0,부산,2024,4,MBS05,신선대부두 5선석,외항,2024-05-01 03:00:00,양적하,2024-05-02 05:00:00,1 days 02:00:00
3,부산,2024,3,MSN06,신항 2부두 3선석,외항,2024-05-01 04:15:00,양적하,2024-05-02 07:00:00,1 days 02:45:00
8,부산,2024,4,MS402,신항 4부두 2선석,외항,2024-04-30 21:40:00,양적하,2024-05-01 23:00:00,1 days 01:20:00
49,부산,2024,17,MB604,자성대부두 64선석,외항,2024-05-01 07:50:00,양적하,2024-05-02 10:00:00,1 days 02:10:00
90,부산,2024,13,MBS02,신선대부두 2선석,외항,2024-04-30 10:15:00,양적하,2024-05-02 07:00:00,1 days 20:45:00
...,...,...,...,...,...,...,...,...,...,...
246955,부산,2025,2,*DP01,선진2조선,외항,2025-07-07 14:00:00,선박수리,2025-07-28 08:00:00,20 days 18:00:00
246984,부산,2025,2,*YQ01,기타 남항 사설조선소,외항,2025-05-22 08:15:00,선박수리,2025-08-30 23:00:00,100 days 14:45:00
247006,부산,2025,6,WAN03,남외항 N-3박지,외항,2025-07-30 09:54:00,적하,2025-07-31 18:00:00,1 days 08:06:00
247021,부산,2025,7,WAN03,남외항 N-3박지,외항,2025-07-29 08:35:00,급유,2025-07-31 07:30:00,1 days 22:55:00
247039,부산,2025,4,WAN03,남외항 N-3박지,외항,2025-07-18 11:15:00,양하,2025-07-22 17:38:00,4 days 06:23:00

In [308]:
df_outer_ratio = round((df_outer[df_outer['예정대기시간'] > df['예정대기시간'].median()].shape[0] / df_outer.shape[0]) * 100, 2)
df_outer_ratio

44.84

In [309]:
df_inner_ratio = round((df_inner[df_inner['예정대기시간'] > df['예정대기시간'].median()].shape[0] / df_inner.shape[0]) * 100, 2)
df_inner_ratio

55.21

In [310]:
df_inner['입항목적'].unique()

<StringArray>
['기타', '양하', '단순경유', '양적하', '선박수리', '급유', '적하', '선용품적재', '승무원교대']
Length: 9, dtype: str

In [339]:
df_inner['입항목적'].value_counts()

total = df_inner['입항목적'].value_counts().sum()

# 화물 작업 관련 목적 : 양하, 적하, 양적하
# 선박 유지보수 및 보급 관련 목적 : 선박수리, 급유, 선용품적재
# 인력 및 운항 관련 목적 : 승무원교대, 단순경유

In [327]:
양하 = df_inner[df_inner['입항목적'] == '양하'].shape[0]
적하 = df_inner[df_inner['입항목적'] == '적하'].shape[0]
양적하 = df_inner[df_inner['입항목적'] == '양적하'].shape[0]

In [328]:
선박수리 = df_inner[df_inner['입항목적'] == '선박수리'].shape[0]
급유 = df_inner[df_inner['입항목적'] == '급유'].shape[0]
선용품적재 = df_inner[df_inner['입항목적'] == '선용품적재'].shape[0]

In [329]:
승무원교대 = df_inner[df_inner['입항목적'] == '승무원교대'].shape[0]
단순경유 = df_inner[df_inner['입항목적'] == '단순경유'].shape[0]

In [428]:
df_inner[df_inner['입항목적'] == '단순경유']

,항구명,년도,항차,계선장소시설코드,계선장소명,외내항구분,입항일자,입항목적,출항예정일시,예정대기시간
95,부산,2024,21,MW501,5물량장 1선석,내항,2024-04-30 23:05:00,단순경유,2024-04-30 23:50:00,0 days 00:45:00
102,부산,2024,37,MW501,5물량장 1선석,내항,2024-04-28 23:45:00,단순경유,2024-04-30 09:45:00,1 days 10:00:00
683,부산,2024,24,MW501,5물량장 1선석,내항,2024-04-29 20:00:00,단순경유,2024-04-30 16:40:00,0 days 20:40:00
813,부산,2024,35,MW501,5물량장 1선석,내항,2024-04-29 04:25:00,단순경유,2024-05-01 05:05:00,2 days 00:40:00
830,부산,2024,4,OLH01,청학안벽,내항,2024-04-16 16:00:00,단순경유,2024-04-25 06:30:00,8 days 14:30:00
...,...,...,...,...,...,...,...,...,...,...
246935,부산,2025,67,MW501,5물량장 1선석,내항,2025-07-27 08:15:00,단순경유,2025-07-29 14:15:00,2 days 06:00:00
246947,부산,2025,85,MW501,5물량장 1선석,내항,2025-07-17 11:05:00,단순경유,2025-07-23 07:28:00,5 days 20:23:00
246969,부산,2025,52,MW501,5물량장 1선석,내항,2025-07-30 08:30:00,단순경유,2025-07-30 15:50:00,0 days 07:20:00
247026,부산,2025,43,MW501,5물량장 1선석,내항,2025-07-28 22:00:00,단순경유,2025-07-29 22:40:00,1 days 00:40:00
247033,부산,2025,33,MW501,5물량장 1선석,내항,2025-07-28 19:15:00,단순경유,2025-07-31 11:35:00,2 days 16:20:00

In [440]:
df_inner['예정대기시간'].sort_values(ascending=False)

90076      730 days 16:00:00
185884     593 days 21:55:00
79854      579 days 07:42:00
60052      530 days 14:05:00
72328      492 days 04:39:00
                 ...
82262     -95 days +11:00:00
82263    -109 days +11:00:00
82264    -123 days +11:00:00
82265    -137 days +11:00:00
54950    -156 days +13:15:00
Name: 예정대기시간, Length: 26504, dtype: timedelta64[us]

In [333]:
화물작업 = 양하 + 적하 + 양적하
선박유지보수 = 선박수리 + 급유 + 선용품적재
인력및운항 = 승무원교대 + 단순경유

In [342]:
화물작업_ratio = round((화물작업 / total) * 100, 2)
선박유지보수_ratio = round((선박유지보수 / total) * 100, 2)
인력및운항_ratio = round((인력및운항 / total) * 100, 2)

In [343]:
print(화물작업_ratio)
print(선박유지보수_ratio)
print(인력및운항_ratio)

37.73
5.34
10.48

In [ ]:
# 화물작업, 선박유지보수, 인력및운항 중앙값 구하고, 중앙값보다 큰 비율이 얼마나 되는지 구한뒤
# 그 비율을 어떻게 줄일 수 있는데 개선안을 작성한다.

In [366]:
df_inner.head(1)

,항구명,년도,항차,계선장소시설코드,계선장소명,외내항구분,입항일자,입항목적,출항예정일시,예정대기시간
46,부산,2024,17,*NB01,남부민방파제,내항,2024-04-19 14:50:00,기타,2024-04-30 05:25:00,10 days 14:35:00

In [396]:
화물작업

9999

In [ ]:
화물작업종류 = ['양하', '적하', '양적하']

화물작업중앙값 = df_inner.loc[
    df_inner['입항목적'].isin(화물작업종류),
    '예정대기시간'
].median()

화물작업데이터 = df_inner[
    df_inner['입항목적'].isin(화물작업종류)
]

화물작업중앙값초과건수 = (
    화물작업데이터['예정대기시간'] > 화물작업중앙값
).sum()

# 화물작업 중에서 어느정도나 중앙값보다 큰지 확인한다

round((화물작업중앙값초과건수 / 화물작업데이터.shape[0]) * 100 , 2)

np.float64(49.96)

In [420]:
선박유지보수종류 = ['선박수리', '급유', '선용품적재']

선박유지보수중앙값 = df_inner.loc[
    df_inner['입항목적'].isin(선박유지보수종류),
    '예정대기시간'
].median()

선박유지보수데이터 = df_inner[
    df_inner['입항목적'].isin(선박유지보수종류)
]

선박유지보수중앙값초과건수 = (
    화물작업데이터['예정대기시간'] > 선박유지보수중앙값
).sum()

# 화물작업 중에서 어느정도나 중앙값보다 큰지 확인한다

round((선박유지보수중앙값초과건수 / 화물작업데이터.shape[0]) * 100 , 2)

np.float64(77.63)

In [421]:
인력및운항종류 = ['승무원교대', '단순경유']

인력및운항종류중앙값 = df_inner.loc[
    df_inner['입항목적'].isin(인력및운항종류),
    '예정대기시간'
].median()

인력및운항데이터 = df_inner[
    df_inner['입항목적'].isin(인력및운항종류)
]

인력및운항중앙값초과건수 = (
    화물작업데이터['예정대기시간'] > 인력및운항종류중앙값
).sum()

# 화물작업 중에서 어느정도나 중앙값보다 큰지 확인한다

round((인력및운항중앙값초과건수 / 화물작업데이터.shape[0]) * 100 , 2)

np.float64(61.62)